### PR TITLE
Don't rely on `ZipInfo.extra`

### LINKED ISSUE #83: Python returning empty `info.extra`
On my machine, https://github.com/obfusk/apksigcopier/blob/master/apksigcopier/__init__.py#L384 is always `b''` on Python 3.11.1, even if there is `extra` data in the zipfile. 
I tried manually inserting `DEADBEEF` after the filename, and `old_xtr` remains `b''`
I don't know what impact this has on the proper functioning of the program.

### PR DESCRIPTION
**Pull request by penn5**
Fixes #83

### CODE REVIEW

**Comment by obfusk** [comment]
Thanks but this is already fixed by fcff62fdabb72575cf2113548c7c3b4ef1bb77ea.

I just haven't had the time to review and merge the [`fixes`](https://github.com/obfusk/apksigcopier/commits/fixes) branch yet.

**Comment by penn5** [comment]
Oh :'(

**Comment by obfusk** [comment]
FWIW, this bug has been present in `apksigcopier` since the very first version and AFAIK has never actually been triggered by any APK found "in the wild". So I did not consider fixing it a high prioriry.

**Comment by penn5** [comment]
That's fine, it didn't affect my case either. I just noticed it while debugging #84.

**Pull request closed without merging**
