### PR TITLE
Change patch_apk to make the code more readable

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by mimi89999** [comment]
@obfusk Could you please review this? I would like to make other changes in that function.

**Comment by obfusk** [comment]
I agree that the current code is not ideal.

But using a context manager is so much better than doing manual cleanup (which should really be in a `finally` block), which is why I wrote it that way.

So I'm sorry but I'm currently not inclined to merge this.

**Comment by mimi89999** [comment]
> But using a context manager is so much better than doing manual cleanup (which should really be in a finally block), which is why I wrote it that way.

OK. I changed my PR to use it.

**Comment by obfusk** [comment]
Thanks!

**Pull request merged**
