### PR TITLE
Add support for apks without v2 signature

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by obfusk** [comment]
This seems to be incomplete.

Also: I was still undecided whether would it be better to use a command-line flag for v1-only instead of detecting the v2 block, so we get a proper error if a v2 signature is supposed to be there but missing.

**Comment by mimi89999** [comment]
> Also: I was still undecided whether would it be better to use a command-line flag for v1-only instead of detecting the v2 block, so we get a proper error if a v2 signature is supposed to be there but missing.

How should the user know if there should be a v2 signature? Should we check the rollback protections? https://source.android.com/security/apksigning/v2?hl=en#rollback-protections

**Comment by mimi89999** [comment]
> This seems to be incomplete.

Why do you think so?

**Comment by obfusk** [comment]
> How should the user know if there should be a v2 signature?

That depends on the use case. For an automated verification system that doesn't have this information (as metadata), maybe having an autodetect option is useful. But you can always use `apksigner` to find out.

But developers generating a signature for an fdroiddata MR for an update to their app should know whether they're using v2 signatures when signing their releases. I certainly do :)

**Comment by obfusk** [comment]
> Why do you think so?

* You only modified `copy`, not `patch`.
* I expect `patch_apk()` to generate an exception when passing `extracted_v2_sig=None`.

**Comment by mimi89999** [comment]
> But developers generating a signature for an fdroiddata MR for an update to their app should know whether they're using v2 signatures when signing their releases. I certainly do :)

Yes, but that would require adding another field to the metadata and updating it whenever a dev decides to change. If you add apksigcopier to fdroidserver without making those other changes, it will beak all apps that are only v1 signed.

**Comment by obfusk** [comment]
> it will beak all apps that are only v1 signed.

How so? The signatures are currently already part of the metadata, so fdroidserver can detect whether it also has a file for the signature block or not when patching.

**Comment by mimi89999** [comment]
> > Why do you think so?
> 
>     * You only modified `copy`, not `patch`.
> 
>     * I expect `patch_apk()` to generate an exception when passing `extracted_v2_sig=None`.

Yes. Sorry. I forgot to add that to the PR because I also modified that function for another PR.

> How so? The signatures are currently already part of the metadata, so fdroidserver can detect whether it also has a file for the signature block or not when patching.

Not always. Apps can also use https://f-droid.org/en/docs/Build_Metadata_Reference/#Binaries

**Comment by mimi89999** [comment]
Those are all the apps using that method:
```
michel@debian:~/git/fdroiddata$ grep -r Binaries: metadata/
metadata/im.zom.messenger.yml:Binaries: https://github.com/zom/Zom-Android/releases/download/%v/Zom-%v-zomrelease-release.apk
metadata/org.jellyfin.mobile.yml:Binaries: https://repo.jellyfin.org/releases/client/android/versions/v%v/jellyfin-android-v%v-libre-release.apk
metadata/info.guardianproject.checkey.yml:Binaries: https://guardianproject.info/releases/Checkey-%v.apk
metadata/info.guardianproject.orfox.yml:Binaries: https://guardianproject.info/fdroid/repo/info.guardianproject.orfox_%c.apk
metadata/eu.bubu1.fdroidclassic.yml:Binaries: https://bubu1.eu/fdroidclassic/fdroid/repo/eu.bubu1.fdroidclassic_%c.apk
metadata/androdns.android.leetdreams.ch.androdns.yml:Binaries: https://github.com/gryphius/androdns/releases/download/v%v/androdns.apk
metadata/chromiumupdater.bamless.com.chromiumsweupdater.yml:    Binaries:https://github.com/bamless/chromium-swe-updater/releases/download/v%v/chromium-swe-updater-%v.apk
metadata/uk.co.keepawayfromfire.screens.yml:Binaries: https://github.com/Cj-Malone/Screens/releases/download/v%v/uk.co.keepawayfromfire.screens-%v.apk
metadata/org.briarproject.briar.android.yml:Binaries: https://briarproject.org/apk/briar-%v.apk
metadata/de.corona.tracing.yml:Binaries: https://bubu1.eu/cctg/fdroid/repo/de.corona.tracing_%c.apk
metadata/com.mishiranu.dashchan.yml:Binaries: https://github.com/Mishiranu/Dashchan/releases/download/%v/Dashchan.apk
metadata/de.schildbach.oeffi.yml:Binaries: https://oeffi.schildbach.de/downloads/oeffi-%v.apk
metadata/nya.kitsunyan.foxydroid.yml:Binaries: https://github.com/kitsunyan/foxy-droid/releases/download/%v/foxy-droid-%v.apk
metadata/com.markuspage.android.certtools.yml:Binaries: https://github.com/netmackan/CertTools/releases/download/v%v/CertTools-v%v-signed.apk
metadata/info.guardianproject.locationprivacy.yml:Binaries: https://guardianproject.info/releases/LocationPrivacy-%v.apk
metadata/rs.ltt.android.yml:Binaries: https://ltt.rs/fdroid/repo/Ltt.rs-%v-release.apk
```

**Comment by mimi89999** [comment]
Only 4 apps have signatures in metadata:
```
michel@debian:~/git/fdroiddata$ find -name signatures
./metadata/de.schildbach.wallet/signatures
./metadata/org.schabi.newpipe/signatures
./metadata/com.tachibana.downloader/signatures
./metadata/de.schildbach.wallet_test/signatures
```

**Comment by obfusk** [comment]
Fixed by 9f7864d instead.

**Comment by obfusk** [comment]
> Not always. Apps can also use https://f-droid.org/en/docs/Build_Metadata_Reference/#Binaries

I know. But fdroidserver doesn't (need to) do signature copying for those, just comparing the contents works.

But maybe there is a way the current process can be improved by using `apksigcopier`?

**Comment by mimi89999** [comment]
> I know. But fdroidserver doesn't (need to) do signature copying for those, just comparing the contents works.

The way `verify_apks` from `fdroidserver/common.py` currently works from the doc:
```

def verify_apks(signed_apk, unsigned_apk, tmp_dir):
    """Verify that two apks are the same

    One of the inputs is signed, the other is unsigned. The signature metadata
    is transferred from the signed to the unsigned apk, and then jarsigner is
    used to verify that the signature from the signed APK is also valid for
    the unsigned one.  If the APK given as unsigned actually does have a
    signature, it will be stripped out and ignored.

```

I thought that it could be replaced by `apksigcopier` as well. I also don't like the way it's done because some files could intentionally be committed from the v1 signature.

**Comment by obfusk** [comment]
> The way `verify_apks` from `fdroidserver/common.py` currently works [...]

And if that fails, it falls back on `compare_apks()`.

So yes, replacing that with `apksigcopier` may be useful (but not strictly necessary as it does currently work, unlike v2 signatures via metadata).

**Comment by obfusk** [comment]
> Only 4 apps have signatures in metadata:

I hope to add my 3 apps to that soon :)

**Pull request closed without merging**
