### PR TITLE
Change extract_v2_sig to read file in blocks

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by obfusk** [comment]
Thanks! That was the optimisation I had in mind. But you forgot to take into account the possibility that the magic bits straddle the boundary between two blocks. Fixed by 8fa92ed2b1920983f12bf80b16a24f678be5ac17, closing.

**Comment by mimi89999** [comment]
> But you forgot to take into account the possibility that the magic bits straddle the boundary between two blocks.

I assumed the signature to be aligned. Not sure if that is a requirement. Also, https://source.android.com/security/apksigning/v2?hl=en#apk-signing-block states that:
> APK is parsed by first finding the start of the ZIP Central Directory (by finding the ZIP End of Central Directory record at the end of the file, then reading the start offset of the Central Directory from the record). The magic value provides a quick way to establish that what precedes Central Directory is likely the APK Signing Block. The size of block value then efficiently points to the start of the block in the file.

Maybe we should only search for EOCD and then for SB magic in the block just before it? That would avoid reading the whole apk if there is no v2 signature.

**Comment by obfusk** [comment]
> I assumed the signature to be aligned. Not sure if that is a requirement.

It may very well be. But I didn't want to make that assumption :)

**Comment by obfusk** [comment]
> Maybe we should only search for EOCD and then for SB magic in the block just before it? That would avoid reading the whole apk if there is no v2 signature.

I was thinking about doing exactly that at some point. But it doesn't seem much of a priority to me.

**Comment by mimi89999** [comment]
> I was thinking about doing exactly that at some point. But it doesn't seem much of a priority to me.

OK, but I think that it would be good to open an issue about it not to forget about that.

**Comment by obfusk** [comment]
> I assumed the signature to be aligned. Not sure if that is a requirement.

We're also reading from the end, which (unless the file size happens to be a multiple of 4096) is not aligned.

**Pull request closed without merging**
